# Generated by Django 4.1.1 on 2022-10-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryterm',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dictionaryterm',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
