# Generated by Django 4.1.1 on 2022-10-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_dictionaryterm_is_main_dictionaryterm_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionaryterm',
            name='is_main',
        ),
        migrations.RemoveField(
            model_name='dictionaryterm',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dictionaryterm',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
