# Generated by Django 4.1.1 on 2022-10-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_remove_dictionaryterm_is_main_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AddField(
            model_name='dictionaryterm',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dictionaryterm',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
